services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Oveleon\ContaoBergheimBundle\:
        resource: '../../'
        exclude: '../../{Model,DependencyInjection,Resources}'
